module.exports = {
	extends: [ '@commitlint/config-conventional' ],
	rules: {
		'type-enum': [
			2,
			'always',
			[
				'feat',
				'fix',
				'refactor',
				'perf',
				'style',
				'test',
				'docs',
				'chore',
				'build',
			],
		],
		'scope-enum': [
			2,
			'always',
			[
				'router',
				'rest',
				'rsvp',
				'gallery',
				'countdown',
				'music',
				'og',
				'theme',
				'cache',
				'security',
				'cf',
				'media',
				'cpt',
				'block',
				'pattern',
				'deps',
				'config',
			],
		],
		'subject-case': [ 2, 'always', [ 'sentence-case', 'lower-case' ] ],
		'subject-max-length': [ 2, 'always', 72 ],
		'subject-empty': [ 2, 'never' ],
		'header-max-length': [ 2, 'always', 100 ],
	},
};
